import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import { PwaUpdatePrompt } from './components/PwaUpdatePrompt'
import './styles.css'
import './timeline.css'
import './add-location.css'
import './top-moon.css'
import './timeline-current.css'
import './home-current-location.css'
import './location-menu.css'
import './location-reorder.css'
import './ten-day.css'
import './monthly-moon.css'
import './monthly-switch.css'
import './monthly-moon-compact.css'
import './weather-model.css'
import './pwa-update.css'
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/><PwaUpdatePrompt/></React.StrictMode>)
